### ISSUE TITLE
How sure are you this will work?

### ISSUE THREAD

**Issue by FlorSanders** [jacobhq/gemma-jetson#1]
I have been looking into getting the new Gemma models running on the Jetson Nano.
Since your last commit mentions "untested, but should work", how certain are you that this will actually work?

As far as I know, the [Transformers Library](https://pypi.org/project/transformers/) this notebook relies on requires `Python>=3.8`, while the Jetson nano only supports `Python==3.6` out of the box. Updating it to a newer version is possible, but to my knowledge requires [building a lot of packages from scratch](https://i7y.org/en/pytorch-build-on-jetson-nano/).

Any thoughts?

**Comment by jacobhq** [comment]
I still haven't tested it, but you can try this for upgrading python: https://jetsonhacks.com/2023/06/12/upgrade-python-on-jetson-nano-tutorial/. You are right, it takes about three hours though - I've tried it before and it's never worked.

An alternative approach is this image: https://github.com/Qengineering/Jetson-Nano-Ubuntu-20-image. I've never used this, but it looks a lot more promising, and Qengineering have a lot of good stuff for the Jetson that I have used in the past.

Give me a day or so and I'll try and get it working again!

**Comment by FlorSanders** [comment]
Thanks for the pointers! 

In the meantime I have explore other routes and was able to [compile llama.cpp for the Jetson](https://gist.github.com/FlorSanders/2cf043f7161f52aa4b18fb3a1ab6022f).  
It deploys TinyLlama fine, but for the Jetson 2GB version the memory just seems insufficient to run gemma still.

If you do get it working on your end, keep me posted.  
However if it's too much effort, don't sweat it since I have my alternative.
